#!/bin/bash -el

if [ $# -lt 2 ]
then
echo "Usage:"
    echo
echo " % $0 <git-repository> <git-ref-id> <envs>"
    exit 1
fi

SOURCE_DIR=/var/lib/tsuru

function do_deploy() {
    if [ -d /home/application/current ]; then
        cd /home/application/current
        git reset --hard
        git fetch origin
        cd -
    else
        git clone $1 /home/application/current
    fi
    cd /home/application/current
    git checkout $2 >/dev/null 2>&1
    cd -
}

function so_dependencies() {
    if [ -f /home/application/current/requirements.apt ]; then
        sudo -E apt-get install $(cat /home/application/current/requirements.apt) -y
    else
        echo "requirements.apt not found."
        echo "Skipping..."
    fi
}

do_deploy $@
so_dependencies
