#!/bin/bash -el

echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile
mkdir /home/application
useradd -m ubuntu -s /bin/bash
chown ubuntu:ubuntu /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
